### ISSUE TITLE
The notification number on the Signal app does not disappears after reading the message from a Matrix client (Element)

### ISSUE THREAD

**Issue by nicfab** [tulir/mautrix-signal#103]
Hi!
Regarding the issue in the subject, I did some tests with the `signald` developer.
Particularly, I run this command (filling the correct values):

`echo '{"type": "subscribe", "account": "<my phone number>", "version": "v1"}' | nc -U /var/run/signald/signald.sock | jq .`

and then, the following one (filling the correct values):

`signaldctl message mark-read -a <my phone number> <sender's phone number> <message timestamp>`

After that, the notification on the Signal app on my smartphone disappeared.
Thus, the `signald` developer said that it's an issue related to the matrix-bridge.
Can you verify, please?

**Comment by tulir** [comment]
Seems to work fine (but as with all ephemeral events, you need to enable double puppeting or the ephemeral events option to bridge them)
