### ISSUE TITLE
Smilies and Umlauts are transimtted to Matrix as questionmarks.

### ISSUE THREAD

**Issue by undercoverturbo** [tulir/mautrix-signal#108]
### Problem
When transmitting umlauts like ä, ö and ü, the message is transmitted to matrix with a ? instead of the umlauts.
The same thing happens for smilies.

### Steps to reproduce
Nothing special, as far as I can tell.

### Expected
Umlauts and smilies are transmitted correctly to matrix.

**Comment by tulir** [comment]
Happens when signald runs with the wrong locale env vars (#28)

**Comment by undercoverturbo** [comment]
Thanks for the quick answer!
