### ISSUE TITLE
ImportError: cannot import name 'ForbiddenKey' from 'mautrix.bridge.config'

### ISSUE THREAD

**Issue by Marcool04** [tulir/mautrix-signal#16]
Hi all,

I've just been setting up mautrix-signal on a Raspberrypi 4 running archlinuxarm.
I'm using an Arch User Repo package called mautrix-signal-git, which is producing a package from a pull off this repo's master branch:

````
# pacman -Qi mautrix-signal-git
Name            : mautrix-signal-git
Version         : r60.935e8da-1
[snip]
````

It's all working fine now, but I had to make a small change to the code to get it the run. When I first tried to create the registration file I was faced with the error in the title, which was further detailed as follows:

````
# runuser -u mautrix-signal -- python -m mautrix_signal -g -c config.yaml -r registration.yaml
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/site-packages/mautrix_signal/__main__.py", line 22, in <module>
    from .config import Config
  File "/usr/lib/python3.8/site-packages/mautrix_signal/config.py", line 21, in <module>
    from mautrix.bridge.config import (BaseBridgeConfig, ConfigUpdateHelper, ForbiddenKey,
ImportError: cannot import name 'ForbiddenKey' from 'mautrix.bridge.config' (/usr/lib/python3.8/site-packages/mautrix/bridge/config.py)
````

A quick `git blame` shows that this line of code has been as it is since initial commit. I `grep`ed around for `"ForbiddenKey"` a bit, and couldn't find it anywhere. So purely on a hunch I removed the two instances of it in the file:

```diff
diff --git a/mautrix_signal/config.py b/mautrix_signal/config.py
index 920cd85..0730d61 100644
--- a/mautrix_signal/config.py
+++ b/mautrix_signal/config.py
@@ -18,8 +18,7 @@ import os
```

```python
 from mautrix.types import UserID
 from mautrix.client import Client
-from mautrix.bridge.config import (BaseBridgeConfig, ConfigUpdateHelper, ForbiddenKey,
-                                   ForbiddenDefault)
+from mautrix.bridge.config import (BaseBridgeConfig, ConfigUpdateHelper, ForbiddenDefault)

 Permissions = NamedTuple("Permissions", user=bool, admin=bool, level=str)

@@ -36,7 +35,7 @@ class Config(BaseBridgeConfig):
         return [
             *super().forbidden_defaults,
             ForbiddenDefault("appservice.database", "postgres://username:password@hostname/db"),
-            ForbiddenDefault("bridge.permissions", ForbiddenKey("example.com")),
+            ForbiddenDefault("bridge.permissions", "example.com"),
         ]
```

…and that works fine 😃

Thanks for this useful plugin!
Regards,
Mark.

**Comment by tulir** [comment]
You need to use the mautrix-python version specified in `requirements.txt`, otherwise it's not guaranteed to work. I've updated the bridge to use the latest version now

**Comment by Marcool04** [comment]
Great, thanks for the info. The AUR package for mautrix-signal uses an other AUR package, python-mautrix-git, as a dependency, which also pulls from the master branch of the matrix-python repo. If I can find a minute I'll take the time to write a PKGBUILD for the latest tags and respect the `requirements.txt` file, that would be the "correct" way to keep up with the upstream inter-dependencies.

Keep up the great work. Thanks again!
