### ISSUE TITLE
No distinction between Signal 'Read by', 'Delivered to' and 'Sent to' messages

### ISSUE THREAD

**Issue by rajil** [tulir/mautrix-signal#33]
Signal mobile app (Android) gives a 'Read by, 'Delivered to' and 'Sent to' status for a message in group conversation. Element/Matrix incorrectly shows 'Seen by' for all the delivered messages. This should be changed to 'Read by'.

**Comment by tulir** [comment]
Probably not a bridge issue: https://gitlab.com/signald/signald/-/issues/104

**Comment by rajil** [comment]
I see the issue on signald is closed. However, I still see that 'Delivered' message on Signal show up as 'Seen' message on Element.

These are the versions i tested.

```
# apt info signald
Package: signald
Version: 0.12.0
Priority: optional

mautrix-signal 0.1.0b2+dev.3852c137
```
