### ISSUE TITLE
Not able to invite signal bot

### ISSUE THREAD

**Issue by PhieF** [tulir/mautrix-signal#34]
Hi

I'm using docker to deploy signal bridge

when inviting signalbot it stays in the invited state but doesn't join

(I've renamed the bot to be sure it was able to communicate with it)

![Capture d’écran de 2021-01-13 14-34-22](https://user-images.githubusercontent.com/26841885/104459044-8049fb00-55ac-11eb-8aad-ca0473e5779b.png)

Thanks for your work !!

**Comment by tulir** [comment]
https://github.com/tulir/mautrix-telegram/wiki/Troubleshooting

Setup issues are easier to debug in the Matrix room: [#signal:maunium.net](https://matrix.to/#/#signal:maunium.net)
