### ISSUE TITLE
Which database to use?

### ISSUE THREAD

**Issue by select** [tulir/mautrix-signal#50]
The install instructions for me were not 100% clear, should I use the same database as matrix synapse or should I create a separate one. 

Creating a separate one would have the advantage that it's easier to see all the tables that the bride uses.

**Comment by rufflepot** [comment]
Always create a separate one for every bridge if possible. It'll save you a lot of headache in the future. I created user mautrix-signal for database mautrix-signal just to keep it simple. This way you can easily nuke the db if you need it without inadvertently destroying stuff unrelated to the bridge.

**Comment by select** [comment]
Thanks alot
