### ISSUE TITLE
Profile Name Sync

### ISSUE THREAD

**Issue by tpeacock19** [tulir/mautrix-signal#56]
I know that the commit mentions a possibility of breaking the profile name sync but after this 64bc5c36a509ba435a0b01cf44afb1b5d2642efd the names in my instance are no longer updating.

**Comment by bmanturner** [comment]
I just installed this today and I only see phone numbers, no names.

**Comment by parsifallo** [comment]
Same here but current version gives me cryptic names like:

kyCFt6Dff7b+SkvvJfkANC+he45oFVWskc5N0qZ2EqueW3MEaw8FONDqyOFXIO79+Hragdnb2rJK1PLM76YtdA2iT/XZ0bUTfS5A2P5ba3yj (Signal)

Even if I set-displayname for users, after restarting the docker image names change back

**Comment by tulir** [comment]
Name sync mostly works now, @parsifallo's bug was a signald bug that was already fixed

**Comment by tchapi** [comment]
On a fresh install, I still haven't got the names - is this expected (as per your previous comment) ?
