### ISSUE TITLE
E2EE from Element to Signal Bridge

### ISSUE THREAD

**Issue by ionwerz** [tulir/mautrix-signal#61]
I'm trying to set up E2E encryption from my Android Element client, when I'm inside the Settings of Signal room there is next message `You don't have permission to enable encryption in this room`, is there ability to activate it?

**Comment by lowkeylone** [comment]
Same here.

**Comment by tulir** [comment]
You need to enable encryption in the bridge first. After doing that, you can either recreate existing portals or make yourself moderator with `!signal set-pl` to enable encryption.
