### ISSUE TITLE
Unexpected type for creating group portal: {type(info)}")

### ISSUE THREAD

**Issue by nowatbuer** [tulir/mautrix-signal#63]
Sometimes a Signal group does not appear in Matrix. Maybe this error I found in  the logs is related to that? 

rootsrv matrix-mautrix-signal[30618]: [2021-02-15 16:26:12,204] [DEBUG@mau.mx] Received Matrix event $a3Tn1ikuAcmEbo0vUW5ouriqkdYFukDHgBjjwVkQCAA from @norbert:466buer.de in !ZFIJsZBZnmGDxaKSMQ:466buer.de
Feb 15 17:26:12 rootsrv matrix-mautrix-signal[30618]: [2021-02-15 16:26:12,432] [DEBUG@mau.portal.d9158a94-0304-4473-91f7-39c6e0a247a1] Handled Matrix message $a3Tn1ikuAcmEbo0vUW5ouriqkdYFukDHgBjjwVkQCAA -> 1613406372211
Feb 15 17:30:48 rootsrv matrix-mautrix-signal[30618]: [2021-02-15 16:30:48,651] [ERROR@mausignald] Exception in event handler
Feb 15 17:30:48 rootsrv matrix-mautrix-signal[30618]: Traceback (most recent call last):
Feb 15 17:30:48 rootsrv matrix-mautrix-signal[30618]:   File "/opt/mautrix-signal/mausignald/signald.py", line 52, in _run_event_handler
Feb 15 17:30:48 rootsrv matrix-mautrix-signal[30618]:     await handler(event)
Feb 15 17:30:48 rootsrv matrix-mautrix-signal[30618]:   File "/usr/lib/python3.8/site-packages/mautrix_signal/signal.py", line 50, in on_message
Feb 15 17:30:48 rootsrv matrix-mautrix-signal[30618]:     await self.handle_message(user, sender, evt.data_message)
Feb 15 17:30:48 rootsrv matrix-mautrix-signal[30618]:   File "/usr/lib/python3.8/site-packages/mautrix_signal/signal.py", line 88, in handle_message
Feb 15 17:30:48 rootsrv matrix-mautrix-signal[30618]:     await portal.create_matrix_room(user, (group_v2_info or msg.group
Feb 15 17:30:48 rootsrv matrix-mautrix-signal[30618]:   File "/usr/lib/python3.8/site-packages/mautrix_signal/portal.py", line 827, in create_matrix_room
Feb 15 17:30:48 rootsrv matrix-mautrix-signal[30618]:     raise ValueError(f"Unexpected type for creating group portal: {type(info)}")
Feb 15 17:30:48 rootsrv matrix-mautrix-signal[30618]: ValueError: Unexpected type for creating group portal: <class 'mausignald.types.Address'>
Feb 15 17:31:51 rootsrv matrix-mautrix-signal[30618]: [2021-02-15 16:31:51,453] [ERROR@mausignald] Exception in event handler
Feb 15 17:31:51 rootsrv matrix-mautrix-signal[30618]: Traceback (most recent call last):
Feb 15 17:31:51 rootsrv matrix-mautrix-signal[30618]:   File "/opt/mautrix-signal/mausignald/signald.py", line 52, in _run_event_handler
Feb 15 17:31:51 rootsrv matrix-mautrix-signal[30618]:     await handler(event)
Feb 15 17:31:51 rootsrv matrix-mautrix-signal[30618]:   File "/usr/lib/python3.8/site-packages/mautrix_signal/signal.py", line 62, in on_message
Feb 15 17:31:51 rootsrv matrix-mautrix-signal[30618]:     await self.handle_message(user, sender, evt.sync_message.sent.message,
Feb 15 17:31:51 rootsrv matrix-mautrix-signal[30618]:   File "/usr/lib/python3.8/site-packages/mautrix_signal/signal.py", line 88, in handle_message
Feb 15 17:31:51 rootsrv matrix-mautrix-signal[30618]:     await portal.create_matrix_room(user, (group_v2_info or msg.group
Feb 15 17:31:51 rootsrv matrix-mautrix-signal[30618]:   File "/usr/lib/python3.8/site-packages/mautrix_signal/portal.py", line 827, in create_matrix_room
Feb 15 17:31:51 rootsrv matrix-mautrix-signal[30618]:     raise ValueError(f"Unexpected type for creating group portal: {type(info)}")
Feb 15 17:31:51 rootsrv matrix-mautrix-signal[30618]: ValueError: Unexpected type for creating group portal: <class 'mausignald.types.Address'>

**Comment by celogeek** [comment]
I've got the same error.

I'm using Synapse 1.27 and latest version of mautrix-signal (master branch)
