### ISSUE TITLE
Docker e2ee bot never joins room

### ISSUE THREAD

**Issue by riddlecp** [tulir/mautrix-signal#64]
Have setup the containers (synapse, signald, and mautrix-signal) as per wiki instructions, but receiving errors when actually messaging the bot for the first time.  Not worried about the details below, will wipe away the databases as soon as a fix is in place to clean everything up.

> [2021-02-16 15:21:05,235] [INFO@mau.init] Initializing mautrix-signal 0.1.0+dev.4228a89a
> [2021-02-16 15:21:05,239] [INFO@mau.init] Initialization complete in 0.18 seconds
> [2021-02-16 15:21:05,239] [DEBUG@mau.init] Running startup actions...
> [2021-02-16 15:21:05,239] [DEBUG@mau.db] Connecting to postgres://signalbridge:password@postgres_db_1/signalbridge
> [2021-02-16 15:21:05,259] [DEBUG@mau.init] Starting appservice...
> [2021-02-16 15:21:05,259] [DEBUG@mau.as] Starting appservice web server on 0.0.0.0:29328
> [2021-02-16 15:21:05,260] [INFO@mau.mx] Ensuring connectivity to homeserver
> [2021-02-16 15:21:05,455] [DEBUG@mau.bridge.e2ee] Logging in with bridge bot user
> [2021-02-16 15:21:05,461] [DEBUG@mau.bridge.e2ee] Found device ID in database: PVMJCSKTVX
> [2021-02-16 15:21:05,548] [INFO@mau.bridge.e2ee] End-to-bridge encryption support is enabled
> [2021-02-16 15:21:05,551] [DEBUG@mau.mx] Initializing appservice bot
> [2021-02-16 15:21:05,556] [INFO@mausignald] Connected to signald v0.12.0+git2021-02-16r81729030.33
> [2021-02-16 15:21:05,573] [DEBUG@mau.bridge.e2ee.client] Starting syncing
> [2021-02-16 15:21:05,600] [INFO@mau.init] Startup actions complete in 0.36 seconds, now running forever
> [2021-02-16 15:21:32,828] [DEBUG@mau.crypto] Sync response said we have 49 signed curve25519 keys left, sharing new ones...
> [2021-02-16 15:21:32,829] [DEBUG@mau.crypto] Uploading 1 one-time keys
> [2021-02-16 15:21:33,026] [DEBUG@mau.crypto] Created inbound session ieIJrWyjVgaVo2U1Qj8WDQOYZA+zBYwn0LHhyeiyoxk for @chris:riddlehome.net (sender key: RmuoNR0qWfkHpCvvQr+FSaI9q2bmFQstCw4USpiLZSE)
> [2021-02-16 15:21:33,160] [DEBUG@mau.crypto] Shared keys and saved account
> [2021-02-16 15:21:33,226] [DEBUG@mau.crypto] Created inbound group session !VVKeFCsOuUUBuFwDAi:riddlehome.net/RmuoNR0qWfkHpCvvQr+FSaI9q2bmFQstCw4USpiLZSE/JtB9z63rgV516tYQSwLT22OkqvP1AeVLgE4roUz+xk4
> [2021-02-16 15:22:32,748] [DEBUG@mau.crypto] Created inbound group session !VVKeFCsOuUUBuFwDAi:riddlehome.net/RmuoNR0qWfkHpCvvQr+FSaI9q2bmFQstCw4USpiLZSE/8aP5CELt1471bYCvLVE63wN2lrTXut1sHLotjzs8JAw
> [2021-02-16 15:22:39,437] [ERROR@mau.bridge.e2ee.client] Failed to run handler
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/client/syncer.py", line 200, in _catch_errors
    await handler(data)
  File "/usr/lib/python3.8/site-packages/mautrix/client/client.py", line 30, in _update_state
    await self.state_store.update_state(evt)
AttributeError: 'NoneType' object has no attribute 'update_state'

**Comment by tulir** [comment]
https://docs.mau.fi/bridges/general/troubleshooting.html
