### ISSUE TITLE
Messages are sent twice to Signal

### ISSUE THREAD

**Issue by rodolpheh** [tulir/mautrix-signal#71]
Since a recent update (it started happening since an update on Friday), messages are sent twice to Signal, at least I can see each of my messages twice in Signal but nobody has said anything so far... I am using the latest images from the docker repository (dock.mau.dev/tulir/mautrix-signal:latest).

I am currently running mautrix-signal 0.1.0+dev.e1baef53 and can see that it's still happening. All my contacts are sleeping now so I can't confirm if they see each message twice too but will edit this message this as soon as I can confirm.

**Comment by celogeek** [comment]
I can confirm that only I receive the message twice. One of them seems buggy (or duplicates) on signal.

**Comment by waclaw66** [comment]
Same here, messages sent from Element appear on Signal Android twice, on Signal Desktop only once.

signald: latest git version
mautrix-signal: 0.1.0

**Comment by tulir** [comment]
signald issue: https://gitlab.com/signald/signald/-/issues/147

**Comment by celogeek** [comment]
Problem fixed in v0.13.0 ! update signald and the problem should be gone.
