### ISSUE TITLE
Connection to homeserver failed

### ISSUE THREAD

**Issue by nicfab** [tulir/mautrix-signal#79]
Hi!
I receive the error in the subject.
I attach: 1) the log file, 2) config.yaml, 3) registration.yaml.
Let me know if you also need the homeserver.yaml file.
[mautrix-signal-error.zip](https://github.com/tulir/mautrix-signal/files/6229953/mautrix-signal-error.zip)
I look forward to hearing from you.

**Comment by nicfab** [comment]
> Did you use docker? Is the bridge on the same host as the Matrix Server?

I don't use docker, and the bridge is on the same host as the Matrix Server.
I followed the instruction here: https://docs.mau.fi/bridges/python/setup/index.html?bridge=signal

**Comment by nicfab** [comment]
And now ... it works!!!
The issue was that I forgot to set up the information in the homeserver.yaml
You can close this issue.
Tks

**Comment by nicfab** [comment]
I'm sorry.
I can't join the room again.
The bridge works, but only if the command `python -m mautrix_signal` is running and the server's connection is open; if I close the server's connection, the bridge stops working.
Why?
Is there a way to leave the bridge also running if I stop the connection with the server?

**Comment by floviolleau** [comment]
Hi,

Just do a systemd daemon service

Kind regards
