### ISSUE TITLE
Media from Signal to Matrix is sent unencrypted in encrypted rooms

### ISSUE THREAD

**Issue by s3lph** [tulir/mautrix-signal#87]
First of all, I'm not sure whether this is an issue specific to mautrix-signal, or an issue with mautrix-python. Please let me know if this belongs in matrix-python instead.

## Description

Due to [a bug in the Matrix client I'm using](https://github.com/mirukana/mirage/issues/202), I've come to realize that messages sent from the mautrix-signal bridge to a end-to-end encrypted Matrix room are encrypted, but if they "contain" media files (such as images), the files themselves are not encrypted and reside on the involved homeservers in unencrypted form.

While this doesn't really matter that much if only one homeserver is involved (since homeserver and bridge are most likely operated by the same persons, and could probably intercept the message anyway, since the bridge has to decrypt everything), it does become a problem in federated setups:

* My main Matrix account resides on a homeserver shared with a few other people.
* Since I explicitly did not want my bridged traffic to become compromised, I'm running the bridge and a second homeserver (hosting **only** bridges & appservices) on infrastructure that's solely under my control.
* I'd now expect that in a federated E2EE room between these two servers, **everything** would be encrypted, however images and other media received via Signal are stored unencrypted on every involved homeserver.

## Expected Behavior
When a bridged Matrix room is E2EE (or in this specific case E2BridgeE), all messages sent to the room by the bridge should be end to end encrypted, **including** all media, e.g. images. I.e. I'd expect something like this (made up example):
```json
{
    "content": {
	"body": "[REDACTED].jpg",
	"file": {
            "hashes": {
                "sha256": "nevergonnagiveyoup"
            },
            "iv": "nevergonnaletyoudown",
            "key": {
                "alg": "AES256ECB",  # don't do this :)
                "ext": true,
                "k": "nevergonnarunaround",
                "key_opts" [
                    0: "desert",
                    1: "you"
                ],
            },
	    "mimetype": "image/jpeg",
	    "url": "mxc://s3lph.me/nevergonnamakeyoucry",
	    "v": "v2",
        },
	"info": {
	    "h": 1200,
	    "w": 1600,
	    "size": 1337
	},
	"msgtype": "m.image",
    },
    "room_id": "[REDACTED]:s3lph.me",
    "type": "m.room.message"
}
```

## Actual Behavior
While the message itself is E2EE, the image itself is not; a raw mxc:// URL is referenced, and the image is stored on homeservers in unencrypted form (decrypted message, dumped from my client):
```json
{
    "content": {
	"body": "[REDACTED].jpg",
	"info": {
	    "blurhash": "[REDACTED]",
	    "h": 1200,
	    "mimetype": "image/jpeg",
	    "thumbnail_url": "mxc://s3lph.me/[REDACTED]",
	    "w": 1600,
	    "xyz.amorgan.blurhash": "[REDACTED]"
	},
	"msgtype": "m.image",
	"url": "mxc://s3lph.me/[REDACTED]"
    },
    "room_id": "[REDACTED]:s3lph.me",
    "type": "m.room.message"
}
```

## How to Reproduce
1. Set up an e2ee bridged room in Matrix & Signal
2. Send an image to the Matrix room (in your Matrix client)
3. Send an image to the Signal group (in Signal)
4. Look at both messages (e.g. Element's "view decrypted source" menu option), and see that only the first message contains key material for the image
5. Look at the files stored on the homeserver (e.g. `/var/lib/matrix-synapse/media/...`), see that one is unreadable, while the other is  a regular image file

**Comment by tulir** [comment]
Did you install all three dependencies required for e2be?

**Comment by s3lph** [comment]
Ugh... apparently Debian's `python3-pycryotodome` package actually ships `pycryptodomex` instead of `pycryptodome` ([bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=886291)), which is exactly the same module, but exported as `Cryptodome` instead of `Crypto`.

Sorry for the noise and thanks for the dependencies pointer.

**Comment by s3lph** [comment]
Thanks for the patch 🎉
