### ISSUE TITLE
no message error (await asyncio.shield(future))

### ISSUE THREAD

**Issue by felixx9** [tulir/mautrix-signal#90]
I managed to relink my  signal account by running `signaldctl account delete <phone number>` and `link`

Before I got an errror, when trying to link. Now this very same error occurs, when I try to send a message.

```
[2021-05-22 22:21:01,227] [DEBUG@mau.mx] Received Matrix event $_.... from @sub.domain.tld in !xxxxxxx:domain.tld
[2021-05-22 22:21:02,315] [ERROR@mau.as] Exception in Matrix event handler
Traceback (most recent call last):
  File "/home/zot/mautrix-signal/lib/python3.8/site-packages/mautrix/appservice/as_handler.py", line 178, in try_handle
    await handler_func(event)
  File "/home/zot/mautrix-signal/lib/python3.8/site-packages/mautrix/bridge/matrix.py", line 460, in int_handle_event
    await self.handle_message(evt.room_id, evt.sender, evt.content, evt.event_id)
  File "/home/zot/mautrix-signal/lib/python3.8/site-packages/mautrix/bridge/matrix.py", line 288, in handle_message
    await portal.handle_matrix_message(sender, message, event_id)
  File "/home/zot/mautrix-signal/lib/python3.8/site-packages/mautrix_signal/portal.py", line 220, in handle_matrix_message
    await self.signal.send(username=sender.username, recipient=self.chat_id, body=text,
  File "/home/zot/mautrix-signal/lib/python3.8/site-packages/mausignald/signald.py", line 137, in send
    await self.request_v1("send", username=username, messageBody=body,
  File "/home/zot/mautrix-signal/lib/python3.8/site-packages/mausignald/rpc.py", line 210, in request_v1
    return await self.request(command, expected_response=command, version="v1", **data)
  File "/home/zot/mautrix-signal/lib/python3.8/site-packages/mausignald/rpc.py", line 204, in request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/home/zot/mautrix-signal/lib/python3.8/site-packages/mausignald/rpc.py", line 201, in _raw_request
    return await asyncio.shield(future)
mausignald.errors.ResponseError: RequestProcessingError: no message, see signald logs
```

**Comment by felixx9** [comment]
same error after `sync` command

```
[2021-05-22 22:42:47,222] [ERROR@mau.portal.........=] Failed to update portal
Traceback (most recent call last):
  File "/home/zot/mautrix-signal/lib/python3.8/site-packages/mautrix_signal/portal.py", line 829, in update_matrix_room
    await self._update_matrix_room(source, info)
  File "/home/zot/mautrix-signal/lib/python3.8/site-packages/mautrix_signal/portal.py", line 866, in _update_matrix_room
    await self.update_info(source, info)
  File "/home/zot/mautrix-signal/lib/python3.8/site-packages/mautrix_signal/portal.py", line 642, in update_info
    info = await self.signal.get_group(source.username, info.id, info.revision or -1)
  File "/home/zot/mautrix-signal/lib/python3.8/site-packages/mausignald/signald.py", line 188, in get_group
    resp = await self.request_v1("get_group", account=username, groupID=group_id,
  File "/home/zot/mautrix-signal/lib/python3.8/site-packages/mausignald/rpc.py", line 210, in request_v1
    return await self.request(command, expected_response=command, version="v1", **data)
  File "/home/zot/mautrix-signal/lib/python3.8/site-packages/mausignald/rpc.py", line 204, in request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/home/zot/mautrix-signal/lib/python3.8/site-packages/mausignald/rpc.py", line 201, in _raw_request
    return await asyncio.shield(future)
mausignald.errors.ResponseError: RequestProcessingError: no message, see signald logs

```

**Comment by frederictobiasc** [comment]
I have the same behaviour. What's your mautrix version?

**Comment by felixx9** [comment]
mautrix-signal 0.1.1+dev.34ec0c0f

**Comment by felixx9** [comment]
i cannot find signald logs ;(
(Ubuntu 20.04.2 LTS)

**Comment by felixx9** [comment]
`zot@zot1:~$ journalctl -f -u signald
-- Logs begin at Mon 2020-10-26 19:07:28 UTC. --
Jun 03 15:38:23 zot1 signald[785]: Jun 03, 2021 3:38:23 PM okhttp3.internal.platform.Platform log
Jun 03 15:38:23 zot1 signald[785]: WARNING: A connection to https://textsecure-service.whispersystems.org/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Jun 03 15:38:24 zot1 signald[785]: Jun 03, 2021 3:38:24 PM okhttp3.internal.platform.Platform log
Jun 03 15:38:24 zot1 signald[785]: WARNING: A connection to https://textsecure-service.whispersystems.org/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Jun 03 15:38:25 zot1 signald[785]: Jun 03, 2021 3:38:25 PM okhttp3.internal.platform.Platform log
Jun 03 15:38:25 zot1 signald[785]: WARNING: A connection to https://textsecure-service.whispersystems.org/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Jun 03 15:38:25 zot1 signald[785]: Jun 03, 2021 3:38:25 PM okhttp3.internal.platform.Platform log
Jun 03 15:38:25 zot1 signald[785]: WARNING: A connection to https://textsecure-service.whispersystems.org/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
Jun 03 15:38:26 zot1 signald[785]: Jun 03, 2021 3:38:26 PM okhttp3.internal.platform.Platform log
Jun 03 15:38:26 zot1 signald[785]: WARNING: A connection to https://textsecure-service.whispersystems.org/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
`
...so it's a signald issue!?

**Comment by felixx9** [comment]
https://gitlab.com/signald/signald/-/issues/29

**Comment by felixx9** [comment]
Sorry - I think I was wrong. It's this error, I think:
`un 03 16:45:07 zot1 signald[785]: 16:45:07.105 [socketlistener] ERROR get_group - error while handling request
Jun 03 16:45:07 zot1 signald[785]: org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: Authorization failed!
Jun 03 16:45:07 zot1 signald[785]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.validateServiceResponse(PushServiceSocket.java:1472) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
Jun 03 16:45:07 zot1 signald[785]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1459) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
Jun 03 16:45:07 zot1 signald[785]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceBodyRequest(PushServiceSocket.java:1444) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
Jun 03 16:45:07 zot1 signald[785]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1386) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
Jun 03 16:45:07 zot1 signald[785]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1380) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
Jun 03 16:45:07 zot1 signald[785]:         at org.whispersystems.signalservice.internal.push.PushServiceSocket.retrieveGroupsV2Credentials(PushServiceSocket.java:2052) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
Jun 03 16:45:07 zot1 signald[785]:         at org.whispersystems.signalservice.api.groupsv2.GroupsV2Api.getCredentials(GroupsV2Api.java:51) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_19.jar:?]
Jun 03 16:45:07 zot1 signald[785]:         at io.finn.signald.storage.GroupsV2Storage.getAuthCredential(GroupsV2Storage.java:51) ~[signald.jar:unspecified]
Jun 03 16:45:07 zot1 signald[785]:         at io.finn.signald.GroupsV2Manager.getGroup(GroupsV2Manager.java:389) ~[signald.jar:unspecified]
Jun 03 16:45:07 zot1 signald[785]:         at io.finn.signald.GroupsV2Manager.getGroup(GroupsV2Manager.java:377) ~[signald.jar:unspecified]
Jun 03 16:45:07 zot1 signald[785]:         at io.finn.signald.clientprotocol.v1.GetGroupRequest.run(GetGroupRequest.java:51) ~[signald.jar:unspecified]
Jun 03 16:45:07 zot1 signald[785]:         at io.finn.signald.clientprotocol.v1.GetGroupRequest.run(GetGroupRequest.java:37) ~[signald.jar:unspecified]
Jun 03 16:45:07 zot1 signald[785]:         at io.finn.signald.clientprotocol.Request.<init>(Request.java:153) [signald.jar:unspecified]
Jun 03 16:45:07 zot1 signald[785]:         at io.finn.signald.SocketHandler.run(SocketHandler.java:143) [signald.jar:unspecified]
Jun 03 16:45:07 zot1 signald[785]:         at java.lang.Thread.run(Thread.java:829) [?:?]
`

**Comment by felixx9** [comment]
I filed this on gitlab: https://gitlab.com/signald/signald/-/issues/180

**Comment by felixx9** [comment]
this should be solved now, within signald
